### ISSUE TITLE
How to use to either %intel or %oneapi compilers from intel-oneapi-compilers package?

### ISSUE THREAD

**Issue by dguibert** [flatironinstitute/nixpack#6] opened 2021-11-16 17:06 UTC
Hi,

I can't figure out how to use to either `%intel` or `%oneapi` compiler from intel-oneapi-compilers package.
I am able to use `%intel` from intel package and `%oneapi` from intel-oneapi-compilers package (I'll push a patch to fix `compilerNameMap` in nixpack.py).
But I'm also interested in using the legacy compilers from intel-oneapi-compilers package.

**Comment by dylex** [comment] 2022-01-05 23:00
Ah, I made the incorrect assumption that each package only provides one compiler type, but clearly this is not true.  The problem is really that `compilerNameMap` itself is insufficient.  We need some way to specify which compiler type a given compiler package should act as. I'll think about that a bit, but it shouldn't be too hard, just a new property on packages for compiler name (e.g., `intel-oneapi-compilers.withPrefs { compilerName = "intel" or "oneapi"; }` kind of thing).

The related issues will be does spack's compiler detection to set `CC` actually work correctly for the various compiler types (or does it need to be overridden like with gcc), and are there ever scenarios where you want two different compilers with the same compiler spec in the same build tree (which has no easy solution as it stands).

I'm not sure about all the changes in #7 but will try to fix the underlying issue first and then go back to it.

Sorry again I didn't notice this for so long.  Hopefully I've now fixed my notification settings but feel free to @ me in the future.

**Closed as completed** 2022-01-16 19:12 UTC

**Comment by dylex** [comment] 2022-01-16 19:16
This can now be done using `depends.compiler = intel-oneapi-compilers.withPrefs { compiler_spec = "intel" or "oneapi" (default); }` or `aocc` (works as-is), or `intel-parallel-studio.withPrefs { compiler_spec = "intel@18.1.2"; }` (needs an explicit version override). This took adding a bit of compiler binary detection based on what spack's detection does, because compiler packages are very inconsistent in how the setup the run environment. This could probably be improved and there may well be other compilers that still don't work.
